spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/travelplanner
spring.datasource.username=tp_user
spring.datasource.password=tp_pass

spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

app.jwt.secret=9vCk3Nw7rP2sX1mQ8tL5zH6dA4fG0jK9bN2pQ7wE
app.jwt.expiration-seconds=86400

geoapify.enabled=true
geoapify.api-key=14490781030841f393e2d2f4dd18f632
geoapify.base-url=https://api.geoapify.com/v2
geoapify.radius-meters=12000
geoapify.limit=100

openrouteservice.enabled=true
openrouteservice.api-key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6Ijk0YzdhNjdhNmE0ODRmY2JiN2E1NGRhZjM1ZGUxNThiIiwiaCI6Im11cm11cjY0In0=
openrouteservice.base-url=https://api.openrouteservice.org
openrouteservice.request-timeout-ms=8000